version: "3.3"

services:
#  sparqlear:
#    depends_on:
#      - virtuoso
#      - postgres
#    links:
#        - virtuoso
#        - postgres
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: ltmartin/sparqlear:latest
#    container_name: sparqlear
#    restart: on-failure
#    tty: true
#    stdin_open: true
#    volumes:
#    - ./data:/sparqlear/data

  virtuoso:
    image: openlink/virtuoso-opensource-7:latest
    restart: always
    volumes:
      - virtuoso_peopleLoop2Dataset:/database
#      - virtuoso_peopleLoopDataset:/database
#      - virtuoso_people2Dataset:/database
#      - virtuoso_peopleDataset:/database
#    - virtuoso_smallimdb:/database
#    - virtuoso-database:/database
    ports:
    - "8890:8890"

  postgres:
    image: postgres:14.2-alpine
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: converter
    volumes:
      - postgres_peopleLoop2Dataset:/var/lib/postgresql/data
#      - postgres_peopleLoopDataset:/var/lib/postgresql/data
#      - postgres_people2Dataset:/var/lib/postgresql/data
#      - postgres_peopleDataset:/var/lib/postgresql/data
#      - postgres_smallimdb:/var/lib/postgresql/data
#      - postgres-database:/var/lib/postgresql/data
volumes:
#  postgres_smallimdb:
#    external: true
#  virtuoso_smallimdb:
#    external: true
#  postgres-database:
#    external: true
#  virtuoso-database:
#    external: true
#  postgres_peopleDataset:
#    external: true
#  virtuoso_peopleDataset:
#    external: true
#  postgres_people2Dataset:
#    external: true
#  virtuoso_people2Dataset:
#    external: true
#  postgres_peopleLoopDataset:
#    external: true
#  virtuoso_peopleLoopDataset:
#    external: true
  postgres_peopleLoop2Dataset:
    external: true
  virtuoso_peopleLoop2Dataset:
    external: true
