version: "3.3"

services:
#  sparqlear:
#    depends_on:
#      - virtuoso
#      - postgres
#    links:
#        - virtuoso
#        - postgres
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: ltmartin/sparqlear:latest
#    container_name: sparqlear
#    restart: on-failure
#    tty: true
#    stdin_open: true
#    volumes:
#    - ./data:/sparqlear/data

  virtuoso:
    image: openlink/virtuoso-opensource-7:latest
    restart: always
    volumes:
    - virtuoso_smallimdb:/database
    ports:
    - "8890:8890"

  postgres:
    image: postgres:14.2-alpine
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: converter
    volumes:
      - postgres_smallimdb:/var/lib/postgresql/data
volumes:
  postgres_smallimdb:
    external: true
  virtuoso_smallimdb:
    external: true
